# Generated by Django 5.2.12 on 2026-03-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gmail',
            new_name='email',
        ),
    ]
