# Generated by Django 5.2.12 on 2026-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_gmail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
